<?php

/**
 * @copyright  Marko Cupic 2020 <m.cupic@gmx.ch>
 * @author     Marko Cupic
 * @package    Test Bundle
 * @licence    MIT
 * @see        https://github.com/markocupic/test-bundle
 *
 */


/**
 * Backend modules
 */
$GLOBALS['TL_LANG']['MOD']['dev_tools'] = 'Entwickler Tools';
$GLOBALS['TL_LANG']['MOD']['test_table'] = ['Autogenerated BE Module', 'Autogenerated BE Module.'];

